import {
  BUNDLED_SKILL_RANK,
  type SkillCandidate,
  type SkillDefinition,
  type SkillProvider,
} from '@deepseek-ai/dsh-skill'

const NAME = 'chart-visualization'
const PROVIDER = 'dsh-plugin-chart'
const DESCRIPTION =
  'Create chart images from structured data with AntV. Use for data visualization requests such as line, bar, pie, scatter, radar, Sankey, network, flow, mind-map, organization, and spreadsheet charts（数据可视化、图表）.'
const INVOCATION = { modelInvocable: true, userInvocable: true } as const

/**
 * AntV chart selection and request-format instructions embedded in the plugin.
 * Adapted from antvis/chart-visualization-skills at
 * d168980d14218c2bf0cd153e111abd404c231482 (MIT).
 */
export const SKILL_CONTENT = [
  '# AntV 图表可视化',
  '',
  '根据用户的数据、分析目标和展示场景选择合适的图表，通过 `antv_chart` 工具生成图片，并将工具返回的 Markdown 图片交付给用户。',
  '',
  '## 工作步骤',
  '',
  '1. 明确用户想比较、观察趋势、分析分布、表达占比、展示层级，还是说明关系与流程。',
  '2. 选择信息表达最清楚的图表类型；不要只因为某种图表更醒目就使用它。',
  '3. 将数据整理成下文规定的字段结构，保留用户提供的真实数值与标签。',
  '4. 调用 `antv_chart`，把完整请求放在 `spec` 对象中。插件会自动添加 API 所需的 `source` 字段。',
  '5. 成功后直接展示工具返回的 Markdown 图片；必要时用一两句话说明图表展示的主要内容。',
  '',
  '不要使用 shell 或 `curl` 绕过 `antv_chart`。不要编造图片 URL。若请求因参数格式失败，按规范修正一次；仍失败时说明错误，不要声称已经生成图表。',
  '',
  '## 图表选择指南',
  '',
  '- **时间序列**：用 `line` 表示趋势，或用 `area` 表示累计趋势；两个不同量纲用 `dual-axes`。',
  '- **比较类**：用 `bar` 做横向分类对比，或用 `column` 做纵向分类对比；频率分布用 `histogram`。',
  '- **占比类**：少量类别用 `pie`，层级占比用 `treemap`。类别太多时不要用饼图。',
  '- **关系与流程**：相关性用 `scatter`，流向用 `sankey`，集合重叠用 `venn`。',
  '- **层级与树形**：组织关系用 `organization-chart`，知识结构用 `mind-map`。',
  '- **专用类型**：',
  '  - `radar`：多个对象的多维指标对比。',
  '  - `funnel`：流程阶段转化。',
  '  - `liquid`：单一百分比或进度。',
  '  - `word-cloud`：文本词频；不用于精确数值比较。',
  '  - `boxplot` / `violin`：统计分布。',
  '  - `network-graph`：复杂节点关系。',
  '  - `fishbone-diagram`：因果分析。',
  '  - `flow-diagram`：流程图。',
  '  - `spreadsheet`：结构化数据表或透视表。',
  '',
  '## 工具调用',
  '',
  '工具名：`antv_chart`',
  '',
  '参数只有一个必填对象 `spec`。`spec.type` 必填，其余字段取决于图表类型。',
  '',
  '示例：',
  '',
  '```json',
  '{',
  '  "spec": {',
  '    "type": "line",',
  '    "data": [',
  '      { "time": "2025-01", "value": 100 },',
  '      { "time": "2025-02", "value": 128 }',
  '    ],',
  '    "title": "月度趋势",',
  '    "axisXTitle": "月份",',
  '    "axisYTitle": "数量"',
  '  }',
  '}',
  '```',
  '',
  '工具成功结果会被渲染为：`![AntV line chart](URL)`。',
  '',
  '## 支持的图表类型',
  '',
  '| 分类   | 图表类型                                                                                          |',
  '| ------ | ------------------------------------------------------------------------------------------------- |',
  '| 比较类 | 条形图 (`bar`)、柱状图 (`column`)、瀑布图 (`waterfall`)、双轴图 (`dual-axes`)                     |',
  '| 趋势类 | 面积图 (`area`)、折线图 (`line`)、散点图 (`scatter`)                                              |',
  '| 分布类 | 箱线图 (`boxplot`)、直方图 (`histogram`)、小提琴图 (`violin`)、漏斗图 (`funnel`)                  |',
  '| 占比类 | 饼图 (`pie`)、水波图 (`liquid`)、词云 (`word-cloud`)                                              |',
  '| 层级类 | 组织架构图 (`organization-chart`)、思维导图 (`mind-map`)、矩形树图 (`treemap`)、桑基图 (`sankey`) |',
  '| 关系类 | 关系图 (`network-graph`)、韦恩图 (`venn`)                                                         |',
  '| 流程类 | 流程图 (`flow-diagram`)、鱼骨图 (`fishbone-diagram`)                                              |',
  '| 多维类 | 雷达图 (`radar`)                                                                                  |',
  '| 表格类 | 表格/透视表 (`spreadsheet`)                                                                       |',
  '',
  '## 通用可选参数',
  '',
  '| 参数            | 类型   | 默认值      | 说明                                 |',
  '| --------------- | ------ | ----------- | ------------------------------------ |',
  '| `theme`         | string | `"default"` | `"default"` / `"academy"` / `"dark"` |',
  '| `width`         | number | `600`       | 图表宽度                             |',
  '| `height`        | number | `400`       | 图表高度                             |',
  '| `title`         | string | `""`        | 图表标题                             |',
  '| `style.texture` | string | `"default"` | `"default"` / `"rough"`（手绘风格）  |',
  '',
  '带坐标轴的图表还支持 `axisXTitle` 和 `axisYTitle`。',
  '',
  '## 各图表的数据格式',
  '',
  '- **`area` / `line`**：`{ time: string, value: number, group?: string }[]`；可选 `stack: boolean`。',
  '- **`bar`**：`{ category: string, value: number, group?: string }[]`；可选 `group` / `stack`，默认 `stack: true`。',
  '- **`column`**：`{ category: string, value: number, group?: string }[]`；可选 `group`（默认 `true`）/ `stack`。',
  '- **`scatter`**：`{ x: number, y: number, group?: string }[]`。',
  '- **`pie`**：`{ category: string, value: number }[]`；可选 `innerRadius: number`，范围 `0-1`。',
  '- **`radar`**：`{ name: string, value: number, group?: string }[]`。',
  '- **`funnel`**：`{ category: string, value: number }[]`。',
  '- **`waterfall`**：`{ category: string, value?: number, isTotal?: boolean, isIntermediateTotal?: boolean }[]`。',
  '- **`dual-axes`**：`categories: string[]`，`series: { type: "column" | "line", data: number[], axisYTitle?: string }[]`。',
  '- **`histogram`**：`number[]`；可选 `binNumber: number`。',
  '- **`boxplot` / `violin`**：`{ category: string, value: number, group?: string }[]`。',
  '- **`liquid`**：`percent: number`，范围 `0-1`；可选 `shape: "circle" | "rect" | "pin" | "triangle"`。',
  '- **`word-cloud`**：`{ text: string, value: number }[]`。',
  '- **`sankey`**：`{ source: string, target: string, value: number }[]`；可选 `nodeAlign`。',
  '- **`treemap`**：`{ name: string, value: number, children?: ... }[]`，最深三层。',
  '- **`venn`**：`{ sets: string[], value: number, label?: string }[]`。',
  '- **`network-graph` / `flow-diagram`**：`{ nodes: { name: string }[], edges: { source: string, target: string, name?: string }[] }`。',
  '- **`fishbone-diagram` / `mind-map`**：`{ name: string, children?: ... }`，最深三层。',
  '- **`organization-chart`**：`{ name: string, description?: string, children?: ... }`，最深三层；可选 `orient: "horizontal" | "vertical"`。',
  '- **`spreadsheet`**：`Record<string, string | number>[]`；可选 `rows` / `columns` / `values` 作为透视表字段。',
  '',
  '## 数据质量与隐私',
  '',
  '- 不要改变、补造或随机生成用户的业务数据，除非用户明确要求使用示例数据。',
  '- 缺少图表所必需的字段时，先根据上下文做安全、明显的映射；无法确定时再向用户确认。',
  '- `antv_chart` 会把 `spec` 发送到配置的外部 HTTP 服务。不要发送密码、令牌、密钥、身份证件、完整个人联系方式或其他不必要的敏感数据。',
  '- 对敏感业务数据优先聚合、匿名化或使用用户配置的私有兼容端点。',
  '',
  '## 交付检查',
  '',
  '在结束前确认：图表类型适合分析目标、字段名符合对应格式、数值没有被改写、标题和坐标轴单位清楚、工具返回了真实 URL，并且最终回复中能看到 Markdown 图片。',
].join('\n')

const CANDIDATE: SkillCandidate = {
  name: NAME,
  description: DESCRIPTION,
  invocation: INVOCATION,
  provider: PROVIDER,
  source: 'bundled',
  rank: BUNDLED_SKILL_RANK,
  locator: NAME,
}

const DEFINITION: SkillDefinition = {
  name: NAME,
  description: DESCRIPTION,
  invocation: INVOCATION,
  provider: PROVIDER,
  source: 'bundled',
  content: SKILL_CONTENT,
}

/** Immutable bundled provider; project and user skills may override it by rank. */
export const skillProvider: SkillProvider = {
  name: PROVIDER,
  list: () => Promise.resolve([CANDIDATE]),
  get: candidate => Promise.resolve(candidate.name === NAME ? DEFINITION : undefined),
}
